language: node_js
notifications:
  hipchat:
    matrix:
    - 6737049b378684a17b185bd7d6bc46@119280
    rooms:
      secure: NfAjqhEj7BpScVAZcKBDQdEPF43lH+CWMj0LSAhLNGUbTJPO/+68rF/kHh4ZWX1cMC+mmRxmAvdQienBQMlZF6fznct/Os4gqrXH/7E7d6bhZkRN4VVX0iUteFXLbx2g4J5QVBryb++c/BkwnWrIobaRhv2DNlY/bfgmxh31NcYxJevA6KvknFlvDK5tOVPPCh5Kn/a+d4sI8+C1cX9/mo25u+SM1laNYQXz43EguVTszeVQz66JwBgEG1gy4GLGC5pl5g7IaDWI06IB7Z5lIhdCshbvsjZAMzd+FIijJy8ix7aZKDAmncujvRrjtFtbsxTSScVGJVvqgt0TIezLnfJI3RWESzCBjm1gSxRUd7+S2mnA3exJyrfh1/c9k7USYsQhsuZ+ygaITwwj2RuIGREELHAKt8xUaXzOGmN/gJ72+6c2H0BLk2bBQP2ner8Bp+zJkUltFxIQsUpJt3GxVva1bQxtEFAsLxI7G9+APOMgcPj8Kii9Dwv9ezXng0b+Fcl7U6GrFkYxsRKuP+AJiJyVZ8Yv5R3pfu44K/TE4DKdvGpXP3aFqa8QwK5hlXmO6dkHKz3rqWOFQzl/XrU2hskKJLAGN3dFicNR/e+NJG38gPVkDEtb6hkrjeEdqRb11c6g6lWq3xWpH3kTkoFqrpyzaSpaS75Ex1DmlcU39Zw=
deploy:
  provider: npm
  email: faiz.hasim+npm@servicerocket.com
  api_key:
    secure: D1M26L3Qoh+iZTP0YiZ8Uw5fzUk/ix2iUVhtq8gsQ77HW/1Dwn1JRbucJky90pcNq1+3YpQDXqOE9yWxbzH4wjTLVJ2DO5xvHB1SZFCUwB8aloATL1ozHRJ2Bditdt6zPvahbOLVKtR4+IVBZDq0OtnjuOZ+WiqW+5IVhzY5ct8tISNIXNWPCaLyN+d90fUCz7E1h4rS21eDp60Te88KQg0hY/zywuUdTutR1Cb746HsEPuTJW8mcZdMnEBJSffgujeXSptmtoGvqhQSIQkErqA4+zaEndsP+5eqoqjSb0V0pDF3nD8qBVQwf48ug6r1fn1P9SPru8fpVzRAcK3R1e41sbmU0Za2ckZNSSFEFv1cD6PbLMdfLaRAQIZMqRttaC5dnv/0xl/Z4VdCqOjbya2Pm8ozWc8rDMYw7QUsxsIb5wAYPOV+unsNVLMcgPzPeQ7xwsnwFj6cMOwtaraILZdoxWJAIV3NKrfWZ7y7r5dU85Nyt7f2pmYjXX6VEbHX4BALIUrG5Yej2KCFqaeKkLmqoCwkG1RTyCXwV5ygY9cdMgfN7RwZejI4BptfoKdZ03hxTnjLQhJ0+F/TabgvX+xq9nRBRV9zYZKqF6rzCX4I4Y/Czduz1kkJ8afyXHXhAKH0hwQb9d5+p7P4uz2Qw4tDW1XVNsPRa+k2alKR3PY=
  on:
    tags: true
