language: node_js
notifications:
  hipchat:
    matrix:
    - 6737049b378684a17b185bd7d6bc46@119280
    rooms:
      secure: NfAjqhEj7BpScVAZcKBDQdEPF43lH+CWMj0LSAhLNGUbTJPO/+68rF/kHh4ZWX1cMC+mmRxmAvdQienBQMlZF6fznct/Os4gqrXH/7E7d6bhZkRN4VVX0iUteFXLbx2g4J5QVBryb++c/BkwnWrIobaRhv2DNlY/bfgmxh31NcYxJevA6KvknFlvDK5tOVPPCh5Kn/a+d4sI8+C1cX9/mo25u+SM1laNYQXz43EguVTszeVQz66JwBgEG1gy4GLGC5pl5g7IaDWI06IB7Z5lIhdCshbvsjZAMzd+FIijJy8ix7aZKDAmncujvRrjtFtbsxTSScVGJVvqgt0TIezLnfJI3RWESzCBjm1gSxRUd7+S2mnA3exJyrfh1/c9k7USYsQhsuZ+ygaITwwj2RuIGREELHAKt8xUaXzOGmN/gJ72+6c2H0BLk2bBQP2ner8Bp+zJkUltFxIQsUpJt3GxVva1bQxtEFAsLxI7G9+APOMgcPj8Kii9Dwv9ezXng0b+Fcl7U6GrFkYxsRKuP+AJiJyVZ8Yv5R3pfu44K/TE4DKdvGpXP3aFqa8QwK5hlXmO6dkHKz3rqWOFQzl/XrU2hskKJLAGN3dFicNR/e+NJG38gPVkDEtb6hkrjeEdqRb11c6g6lWq3xWpH3kTkoFqrpyzaSpaS75Ex1DmlcU39Zw=
deploy:
  provider: npm
  email: faiz.hasim+npm@servicerocket.com
  api_key:
    secure: vS9pr9TO7vJ4evyCGl1FF4Ta+UbyBvYOLmmJQ+3Qbwk8KgZteTU1S+GjMY1Km3nedcatpyX0K42IVEiA7so+38sp7Aer9Hv/YDBvpmgyuUecrV8mftEBiDHsL9A6rE3oJglx/8nRbNmVWFTNmb4BPkUAlHGIUWaKZ+QOuxJzr3FwCP29eLHJHd0UghGyHyP7/0bWGDA2lZuAIkXOimiHB/TnBayYcDHL6khEDqhpuef9EgdcyQNJKWJA8GsC0D8z9UsKDpd5xhGUgoWD/CgAygq8gXmrjvux6MJGezyUkGmBpMTbsGhtgW/wCXCcZuR+62NvwOG1zh6+j8R4PZsr23xeC29P4HJTngXCgfHIzEri18TV9RRJP2BD77A5GmCMxx35O6h06jhb/RzhkqtGaHchkVsqtDUuycXs01Y1hxWUalXfBE5+0lrPALnd/AV0eFpfL+5CdK3ko5tmDc2Z3NyXx32aGlGsNP/xwEy9kkBMM8mh1+ymQhLs9IxPBHyfD7N1v/A9lJyprXhkBgaC1aW9Gk+3Z/CaaYu5aEt0w8TFK7vkFFNqxuJ7l0Dh+5oyDX1m7MCSxdeyB26lEp5jNpXFJimNRCQ7syfdXjGhoac0WA+JIEhweL6JN2YbzJwutp+OpgEuTlR+eB7wtufyF2ECBKA1NZDKQ1ktlXKTqxQ=
  on:
    tags: true
